image: bradrydzewski/python:2.7
services:
  - postgres

notify:
  email:
    recipients:
      - baron@baronchandler.com

script:
  - make
  - make test

deploy:
  ssh:
    cmd: git clone https://github.com/VentureCranial/PawTrain.git deploy && make -C deploy deploy
