image: bradrydzewski/python:2.7
cache:
  - /var/tmp/pip-cache/

script:
  - mkdir -p /var/tmp/pip-cache/
  - sudo chown -R ubuntu:ubuntu /var/tmp/pip-cache/

services:
  - postgres

notify:
  email:
    recipients:
      - baron@baronchandler.com

script:
  - make
  - make test

deploy:
  ssh:
    target: pawtrain@docker-01:pawtrain.tar.gz
    artifacts: GITARCHIVE
    cmd: tar zxf pawtrain.tar.gz && make -C PawTrain deploy
