image: bradrydzewski/python:2.7
cache:
  - /var/tmp/pip-cache/
services:
  - postgres
env:
  - FACEBOOK_ID={{FACEBOOK_ID}}
  - FACEBOOK_SECRET={{FACEBOOK_SECRET}}
  - LINKEDIN_ID={{LINKEDIN_ID}}
  - LINKEDIN_SECRET={{LINKEDIN_SECRET}}
  - TWITTER_ID={{TWITTER_ID}}
  - TWITTER_SECRET={{TWITTER_SECRET}}
script:
  - mkdir -p /var/tmp/pip-cache/
  - sudo chown -R ubuntu:ubuntu /var/tmp/pip-cache/
  - chmod +x mk_oauth_fixtures.sh
  - ./mk_oauth_fixtures.sh
  - psql -h localhost -c 'create database test;' -U postgres
notify:
  email:
    recipients:
      - baron@baronchandler.com
script:
  - make
  - make test
deploy:
  ssh:
    target: pawtrain@docker-01:/home/pawtrain/pawtrain.tar.gz
    artifacts:
      - GITARCHIVE
    cmd: sh -c "cd /home/pawtrain && tar zxf pawtrain.tar.gz && make -C PawTrain deploy-fast"
