image: bradrydzewski/python:2.7
services:
  - postgres

notify:
  email:
    recipients:
      - baron@baronchandler.com

script:
  - make
  - make test

deploy:
  ssh:
    target: pawtrain@docker-01:deploy
    cmd: cd deploy && make deploy
