image: bradrydzewski/python:2.7
cache:
  - /var/tmp/pip-cache

services:
  - postgres

notify:
  email:
    recipients:
      - baron@baronchandler.com

script:
  - make
  - make test

deploy:
  ssh:
    target: pawtrain@docker-01:deploy
    cmd: git clone https://github.com/VentureCranial/PawTrain.git deploy && make -C deploy deploy
